### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by storkk** [dogsheep/pocket-to-sqlite#13]
Fresh install from pip: pocket-to-sqlite, version 0.2.3

```
$ pocket-to-sqlite fetch pocket.db
  [------------------------------------]  31/4625  1d 23:30:14
Traceback (most recent call last):
  File "/home/storkk/pocket/venv/bin/pocket-to-sqlite", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/pocket_to_sqlite/cli.py", line 101, in fetch
    utils.save_items(bar, db)
  File "/home/storkk/pocket/venv/lib/python3.12/site-packages/pocket_to_sqlite/utils.py", line 18, in save_items
    "author_id": int(details["author_id"]),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Brian Hayes'
```

**Comment by storkk** [comment]
Here is the details item, in case that helps:
```
{
    "author_id": "Brian Hayes",
    "name": "Brian Hayes",
    "url": "http://bit-player.org/author/brian",
    "item_id": "68155386"
}
```

If Pocket changed their internal representation to something more normalized in the time since it became a Mozilla project, then it's possible this is some kind of legacy format, or some format Pocket have introduced to help their new systems parse legacy saves. No idea, just grasping at straws at how an "id" field could contain the string representation... but most of my saved pages will have been from >10 years ago.
